### ISSUE TITLE
Tweet not processed yet

### ISSUE THREAD

**Issue by kuchaale** [dennissergeev/atmosscibot#13]
I submitted [this tweet](https://twitter.com/kuchaale/status/1411987441439944706) yesterday. However, the request has not been processed yet. Is it still in the queue? Thx

**Comment by dennissergeev** [comment]
hi @kuchaale. Thanks for submitting this issue report. I am not sure why your tweet hasn't been picked up by the bot - it should happen within ~3h max. I also checked the bot's notifications on Twitter and there was nothing from you. 

I've just tweeted the same and the bot responded (I deleted those tweets though). So try deleting your original tweet and trying again.

**Comment by kuchaale** [comment]
I deleted my original tweet and tried again [here](https://twitter.com/kuchaale/status/1412437402224844814). I am still waiting though :(

**Comment by dennissergeev** [comment]
sorry about this @kuchaale!

I can't see anything wrong with your tweet so I'm at a loss why it's not being picked up by twitter's API. Do you perhaps have your twitter settings in a way that not everyone can reply to them or something like that?

I've just tried tweeting your request to the bot and it worked: https://twitter.com/meteodenny/status/1412504933996302337?s=20

**Comment by kuchaale** [comment]
You're right. I had to change ["quality filter"](https://twitter.com/settings/notifications/filters). You can delete your tweet if you wish.
